( define (problem platform_stacking)
	( :domain dock_domain )
	( :objects
		c1 c2 c3 p1 p2 p3 t1
	)
	(:init
		( container c1 )
		( container c2 )
		( container c3 )
		( truck     t1 )
		( platform  p1 )
		( platform  p2 )
		( platform  p3 )
		( on c2 p2 )
		( on c1 p1 )
		( on c3 p1 )
		( on t1 p2 )
		( on c3 c1 )
		( adj p1 p2 )
		( adj p1 p3 )
		( free t1 )
		( free c2 )
		( free c3 )
		( free p1 )
		( free p3 )
		( has_container_below c3 )
	)
	(:goal
		(and
			( on c1 c2 )
			( on c1 p3 )
			( on c2 p3 )
			( on c3 p3 )
			( on t1 p1 )
			( free p3 )
			( free p2 )
			( free c1 )
			( free c3 )
		)
	)
)